### ISSUE TITLE
N64 filter

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#10]
I've always planned to get a 3-point filter working with shaders.  I haven't gotten around to it yet, but I am open to either internal or external shader support for this.  A lot of architecting needs to happen to properly support GLSL vertex shaders.

**Comment by Wolf3s** [comment]
> 

SDL2 Could handle with filters however sounds like it's limited.

**Comment by atsb** [comment]
It is extremely limited, in this case, for the OpenGL context to render it, it would need to be a GLSL shader loaded via OpenGL.  I did attempt one a few weeks ago but it just crashed, this is probably going to be a long-term thing.

The renderer itself also needs a whole bunch of fixing, perhaps even bumping it up to a GLES renderer would be better.  Most of it is handled by SDL_opengl so it shouldn't be too much of a hassle

**Comment by atsb** [comment]
Not going to happen anytime soon.

**Comment by atsb** [comment]
And it is finally DONE!!!!
