### ISSUE TITLE
Add a better way to support Doom64EX+ for other platforms

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#101]
This issue is a continuation of issue #99 that now we better think about the opengl itself

**Comment by atsb** [comment]
GLES renderer instead of OPENGL 2.1?  Similar to what GZDOOM did for lower end platforms

**Comment by Wolf3s** [comment]
> GLES renderer instead of OPENGL 2.1? Similar to what GZDOOM did for lower end platforms

No, the gles renderer should be a option.

**Comment by atsb** [comment]
Agreed.  We can have a renderer choice for most systems, and for those that would 'only' support GLES, have it as the only option.  Like for Android and embedded devices like small single board computers where GLES would make a lot more sense.

**Comment by Wolf3s** [comment]
> Agreed. We can have a renderer choice for most systems, and for those that would 'only' support GLES, have it as the only option. Like for Android and embedded devices like small single board computers where GLES would make a lot more sense.

Yeah and there´s much more to do about the shaders also.
