### ISSUE TITLE
Fix opengl on other platforms

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#104]

**Comment by atsb** [comment]
I tested it on Linux.  I’ll do a push tomorrow with some fixes but from what I saw, apart from that one issue it should boot up fine once solved

**Comment by Wolf3s** [comment]
> I tested it on Linux. I’ll do a push tomorrow with some fixes but from what I saw, apart from that one issue it should boot up fine once solved

Ok, thanks for the info

**Comment by atsb** [comment]
Let’s keep this open though just in case.  Either way Unix platforms will need a good amount of testing

**Comment by Wolf3s** [comment]
> Let’s keep this open though just in case. Either way Unix platforms will need a good amount of testing

Yep and a great rewrite
