### ISSUE TITLE
Textures sometimes don't render at the edges of the screen when using a high fov

### ISSUE THREAD

**Issue by JamesC0222** [atsb/Doom64EX-Plus#111]
Not sure how much of a problem this is for most users, but I've noticed that when I set the FOV in the config file to 120 (my preferred FOV for this game) I have weird visual effects like this. Checked with the default FOV and this doesn't happen. 

![Doom64EX-Plus - Version Date_ Dec 14 2022 12_28_2022 7_00_12 PM](https://user-images.githubusercontent.com/81458830/209886873-c4ab9852-2b86-496b-ac0a-0d010d5ba011.png)

**Comment by Wolf3s** [comment]
> Not sure how much of a problem this is for most users, but I've noticed that when I set the FOV in the config file to 120 (my preferred FOV for this game) I have weird visual effects like this. Checked with the default FOV and this doesn't happen.
> 
> ![Doom64EX-Plus - Version Date_ Dec 14 2022 12_28_2022 7_00_12 PM](https://user-images.githubusercontent.com/81458830/209886873-c4ab9852-2b86-496b-ac0a-0d010d5ba011.png)

Did you activated the accessbility?

**Comment by JamesC0222** [comment]
The problem occurs whether accessibility is on or not. It wasn't on when this was taken. The reason the screen is like that is because I had picked up an invulnerability sphere. In retrospect, I probably should've waited for it to wear off before I reported a graphic bug.

**Comment by atsb** [comment]
[DOOM64EX+.zip](https://github.com/atsb/Doom64EX-Plus/files/10318583/DOOM64EX%2B.zip)

How does this work for you?

![sshot010](https://user-images.githubusercontent.com/44937323/209930248-d21c843c-0232-4242-aadd-4a27770486f0.png)

My FOV at 140 :)

**Comment by atsb** [comment]
![sshot011](https://user-images.githubusercontent.com/44937323/209930821-f4458a75-f20a-4b89-8b8e-ab82cd29f26a.png)

Also on The Absolution

**Comment by JamesC0222** [comment]
Works perfectly.  Thanks! I think I've found my new favorite port of this game!
