### ISSUE TITLE
Fully replace SDL callback with something else for fluidlite

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#115]
Making this to document and track it.  I’ve done as much as I can about the sdl2 callback to fluidsynth but every now and then it crashes the game within the callback.

We definitely should replace it.  Maybe with the mus2mid code of chocolate doom?  It’s probably the most compatible

**Comment by Wolf3s** [comment]
What about fluidlite?

**Comment by atsb** [comment]
If we can get a good audio implementation going with fluidlite then that’s fine.  It’s just the sdl2 callback isn’t so stable.  Maybe an openal or SDL Mixer version would be better.  I do really like fluidlite, it’s only this one little issue that creeps up.

**Comment by atsb** [comment]
The fluidlite repo has some examples in their issues with things like using Sokol audio alongside.  But I haven’t had much success with using the code

**Comment by atsb** [comment]
Here: https://github.com/divideconcept/FluidLite/issues/22

**Comment by Wolf3s** [comment]
> If we can get a good audio implementation going with fluidlite then that’s fine. It’s just the sdl2 callback isn’t so stable. Maybe an openal or SDL Mixer version would be better. I do really like fluidlite, it’s only this one little issue that creeps up.

This cool because this opens a lack of possibilities of porting

**Comment by atsb** [comment]
It’s very flexible and portable yeah, probably something with how we are using it is the issue

**Comment by bfg01** [comment]
Sorry beforehand for the noob question; but, would this be related to finally making it completely independent of pulseaudio on Linux, and instead -or at least as option- sound working with ALSA or Apulse?

**Comment by atsb** [comment]
Sadly no.  Fluidlite still uses libpulse for midi, so it will always require at least that, unless we completely remove the sound backend and code another one.

**Comment by atsb** [comment]
Ok so for now, I'm using Kaiser's fluidsynth version which is based on the 1.1 series rather than fluidlite which is much more recent.  One of the functions was changed completely between these versions and would crash EX+ - Kaiser's version does not.

@bfg01 - to solve the pulseaudio issue, I will compile versions of Kaiser's fluidsynth library for x64 linux and will do that on Debian so it would be using older LIBC versions, which should be compatible with nearly everyone.  I'll bundle it into the repo and change the build scripts to link to it.  This way, it would be using SDL2 for all audio and fluidsynth only for reading the MIDI tracks.

**Comment by Wolf3s** [comment]
Closed because the issue #151 is the continuation of this one.
