### ISSUE TITLE
For underterminated time

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#118]
I tried to fix the linux build on the every form, every way, even punch into the wall 200 times per day and no results so yeah this time unfortunally i give up on this one.

**Comment by atsb** [comment]
One thing I learned about the Doom engine in general.  Do too much and you'll destroy it :D

This is what I prefer with the Wolfenstein engine, it is a lot more difficult to mess up, because it is simpler.

**Comment by atsb** [comment]
I have now, changed the default branch from main to stable, so that folks who want to pull or use it don't have to fish out a version for Linux.  This gives us freedom to try things to get it working without the stress of being the main branch.

**Comment by Wolf3s** [comment]
> Reference

UPDATE: It´s working on linux properly it´s the `censored` dir system of SDL2 that sucks
https://youtu.be/F_8CIAY0fO4

**Comment by atsb** [comment]
I’ll try it too, looks better and doesn’t give the leaf error at least
