### ISSUE TITLE
How to convert original dumped ROM to WAD?

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#12]
A while ago there used to be a kind of converter from original dumped ROM to a WAD Doom64EX-Plus can read. Is this still possible? Can this be natively done on Linux?

And additionally, could it be possible to customize the save data location? So instead of $XDG_DATA_HOME/doom64ex-plus, telling it to save within doom64ex-plus directory itself or somewhere else.

Thanks again.

**Comment by atsb** [comment]
Doom64EX-Plus has dropped support for the N64 ROM, I only support the IWAD from the remaster now.  Save directory I can modify.
