### ISSUE TITLE
[Fixed] [Stable] Missing reference on A_

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#123]

**Comment by atsb** [comment]
A_ what?

**Comment by atsb** [comment]
*this is the start of a bad joke*

**Comment by Wolf3s** [comment]
> A_ what?

https://github.com/atsb/Doom64EX-Plus/blob/6e25f2f9b12dd2525d8fdd37051d00731b82bf4a/src/engine/info.c#L149

**Comment by Wolf3s** [comment]
This guy doesn´t have proper initialization on msvc when i was reconciling with the wolfy(Failed) branch.

**Comment by Wolf3s** [comment]
> _this is the start of a bad joke_

No ;)

**Comment by atsb** [comment]
They all don't.  There is a good reason for this, these are hacky pointers that are also used in dehacked.  I know most are mobj_t but I'm leaving them solely as pointers.

**Comment by Wolf3s** [comment]
> They all don't. There is a good reason for this, these are hacky pointers that are also used in dehacked. I know most are mobj_t but I'm leaving them solely as pointers.

I could put this guys in info.h instead of there.

**Comment by atsb** [comment]
Then it wouldn't work because dehacked has to see them.  These are things that can't really be touched without breaking other things.  You can try however and see what breaks or if it stays the same.  I've never touched it as this is something Doom has always had, so I've always left it as is.

**Comment by atsb** [comment]
@wolfysdl - I took a look just now at the choco dehacked stuff I pulled in and we don’t need the pointers there for dehacked.  The only issue I’d see is then in the info.c code where the attacks are used, they are all used as void.  This might cause an issue if we change them to accurate prototypes.  But moving them to a header file should be ok.

**Comment by Wolf3s** [comment]
> @wolfysdl - I took a look just now at the choco dehacked stuff I pulled in and we don’t need the pointers there for dehacked. The only issue I’d see is then in the info.c code where the attacks are used, they are all used as void. This might cause an issue if we change them to accurate prototypes. But moving them to a header file should be ok.

Hey, becareful when you do this since some of your changes just break the Linux.

**Comment by atsb** [comment]
Linux works fine from stable.

**Comment by Wolf3s** [comment]
> Linux works fine from stable.

I know but i'm warning you.

**Comment by atsb** [comment]
😅
