### ISSUE TITLE
[Wolfy] - Broken Save/Load functionality

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#140]
This needs to be fixed.

**Comment by Wolf3s** [comment]
> This needs to be fixed.

Possibly this one is easy, maybe it's the nath lib.
Update: it´s the glm lib

**Comment by SumatraPeter** [comment]
Curious what this open issue's about, since in my limited testing so far saving and loading games seems to work fine as of 3.6.5.7?

**Comment by Wolf3s** [comment]
> Curious what this open issue's about, since in my limited testing so far saving and loading games seems to work fine as of 3.6.5.7?

It's from my branch.

**Comment by SumatraPeter** [comment]
So nothing that affects the main release (yet)? Got it.

**Comment by Wolf3s** [comment]
> So nothing that affects the main release (yet)? Got it.

Yeah
