### ISSUE TITLE
Changing Interpolation setting freezes the game

### ISSUE THREAD

**Issue by bubbleguuum** [atsb/Doom64EX-Plus#145]
Version: 3.6.5.3 Windows Zip downloaded on 01/14/2023.

Changing the Interpolation setting in Video settings freezes the game in that setting page. Sound can still be heard when using arrow keys but the game does not have the focus or something and must be killed.

**Comment by atsb** [comment]
Yep, got that.  I've added a GL_Init and Refreshing the video menu which makes it not happen as often.  I had to change it about 4 times before it messed up.  It is something in the interpolate code doing this to the menu and isn't a simple 'full fix'.  But this makes it so if you set it on or off once or twice and leave it, then it is fine.

It will be in the next build.

**Comment by atsb** [comment]
Should be fixed in RC2

**Comment by bubbleguuum** [comment]
Confirming !

**Comment by atsb** [comment]
Hooorah!!!!  Finally :)
