### ISSUE TITLE
Lighting incorrect in a room in Doom Reloaded (AtomicFrog) mod

### ISSUE THREAD

**Issue by bubbleguuum** [atsb/Doom64EX-Plus#148]
Version: 3.6.5.3 Windows Zip downloaded on 01/14/2023.

While comparing the latest version of Doom Reloaded (by AtomicFrog) between the Remaster and the compatible EX+ version from moddb, in the room just before the EXIT in the "Staging Area" level, I found a rendering bug in the rotating light of that room: 

[Screenshot comparison](https://imgur.com/a/TWAsBL6)  (Top: remaster, bottom: EX+)

Note that for the orginal version of that level (which is much different: brighter and yellow-ish), that room lighting is identical in both the Remaster and EX+, so this seems to be a mod specific bug (maybe in the conversion ?).

**Comment by atsb** [comment]
This is due to the Texture Combiners being removed in EX+ (the remaster uses shaders to do it).  Texture Combiners are not well supported today.  This can be fixed by explicitly using the correct lighting and thing light that is wanted.

@wolfysdl - do you think we should add the texture combiners back in?  It does look pretty ugly.

A permanent fix would be us using shaders to mimic this, but it won’t be anytime soon.

**Comment by Wolf3s** [comment]
> This is due to the Texture Combiners being removed in EX+ (the remaster uses shaders to do it). Texture Combiners are not well supported today. This can be fixed by explicitly using the correct lighting and thing light that is wanted.
> 
> @wolfysdl - do you think we should add the texture combiners back in? It does look pretty ugly.
> 
> A permanent fix would be us using shaders to mimic this, but it won’t be anytime soon.

Yes, but temporarily since nowadays we don´t use this arb textures i will do some experiments to change alpha to blend and see if fix it.

**Comment by Wolf3s** [comment]
https://user-images.githubusercontent.com/75867486/212746177-b6b41492-6249-463a-9fd9-cadb7c844ea2.mp4

**Comment by atsb** [comment]
Looks like a winner!  Most of the problem is from the 'white' hue on the sprites and the floor.

**Comment by Wolf3s** [comment]
> Looks like a winner! Most of the problem is from the 'white' hue on the sprites and the floor.

This was tested on wolfy math branch.

**Comment by Wolf3s** [comment]
I will send a "hotfix" build soon.

**Comment by atsb** [comment]
It definitely looks better than before

**Comment by Wolf3s** [comment]
https://drive.google.com/file/d/1iEe8kfvaJhzOhKQYiJ26xIckvzdJPgFC/view?usp=share_link @bubbleguuum

**Comment by bubbleguuum** [comment]
@wolfysdl 

Windows Defender on Windows 11 detects Trojan:Script/Wacatac.H!ml and removes the .rar as soon as I open it.

Probably a false positive as VirusTotal detects nothing: 

https://www.virustotal.com/gui/file/bc5f4f5353f83536d23b146e9f0a153ce09e1f437fcc9742bb120aeaa5534e11?nocache=1

**Comment by Wolf3s** [comment]
> @wolfysdl 
> 
> Windows Defender on Windows 11 detects Trojan:Script/Wacatac.H!ml and removes the .rar as soon as I open it.
> 
> Probably a false positive as VirusTotal detects nothing: 
> 
> https://www.virustotal.com/gui/file/bc5f4f5353f83536d23b146e9f0a153ce09e1f437fcc9742bb120aeaa5534e11?nocache=1

False positive!!!

**Comment by bubbleguuum** [comment]
Indeed. If I unpack the rar and manually scan the files with Defender it does not find anything.

Anyway, when I launch  DOOM64EX+.exe, the game does not start and exits immediately. Started in a shell, nothing is printed.

**Comment by Wolf3s** [comment]
> Indeed. If I unpack the rar and manually scan the files with Defender it does not find anything.
> 
> Anyway, when I launch DOOM64EX+.exe, the game does not start and exits immediately. Started in a shell, nothing is printed.

well i've experienciated this problem too i think i need to create a issue about this but anyway it works pretty well on my PC.

**Comment by atsb** [comment]
did you push this anywhere?

**Comment by Wolf3s** [comment]
> did you push this anywhere?

?

**Comment by atsb** [comment]
The fix :)

**Comment by Wolf3s** [comment]
> The fix :)

not yet i gave up(for now)

**Comment by atsb** [comment]
This is now fixed in the latest release
