### ISSUE TITLE
Beta64 and The Unmaking conversions crashing...

### ISSUE THREAD

**Issue by PerseusAegis** [atsb/Doom64EX-Plus#160]
Beta64 and The Unmaking conversions crash when activating switches in their first levels. Beta64 crashes when activating the next switch behind the blue door in the first level, and The Unmaking crashes in the first level when activating the exit switch. This happens in D64EX Plus versions 3.6.5.4 & 3.6.5.3. Don't know if it's a problem with the converted wads, D64EX Plus, or something else.

**Comment by atsb** [comment]
Fixed.  I have updated the 3.6.5.4 release.

Apolgies for this regression, seems the vanilla code I added into EX+ did not play nicely with some maps on switch texture change and checking use height.

**Comment by PerseusAegis** [comment]
> Fixed. I have updated the 3.6.5.4 release.
> 
> Apolgies for this regression, seems the vanilla code I added into EX+ did not play nicely with some maps on switch texture change and checking use height.

Yep, that fixed it. Much thanks!
