### ISSUE TITLE
Activated switch texture incorrect...

### ISSUE THREAD

**Issue by PerseusAegis** [atsb/Doom64EX-Plus#161]
Minor issue, but this activated switch is using the wrong texture. First image is before activating the switch. Second is after activating, but is using the wrong texture. Third is an example of the correct activation texture of this switch.

Issue seems to happen in all wads, vanilla or custom, with this particular switch texture. Running the 3.6.5.4 version.

![D64Switch](https://user-images.githubusercontent.com/88910929/214439527-7fa40034-e9e5-4bd7-8ef7-3d0646d7fbb6.jpg)
![D64SwitchActivateWrong](https://user-images.githubusercontent.com/88910929/214439532-f2aa3c5b-3376-4eb7-84cc-632226fa1521.jpg)
![D64SwitchActivateCorrect](https://user-images.githubusercontent.com/88910929/214439546-c47e97a5-f7e2-4a4f-9391-6733558cd675.jpg)

**Comment by Wolf3s** [comment]
> Minor issue, but this activated switch is using the wrong texture. First image is before activating the switch. Second is after activating, but is using the wrong texture. Third is an example of the correct activation texture of this switch.
> 
> Issue seems to happen in all wads, vanilla or custom, with this particular switch texture. Running the 3.6.5.4 version.
> 
> ![D64Switch](https://user-images.githubusercontent.com/88910929/214439527-7fa40034-e9e5-4bd7-8ef7-3d0646d7fbb6.jpg) ![D64SwitchActivateWrong](https://user-images.githubusercontent.com/88910929/214439532-f2aa3c5b-3376-4eb7-84cc-632226fa1521.jpg) ![D64SwitchActivateCorrect](https://user-images.githubusercontent.com/88910929/214439546-c47e97a5-f7e2-4a4f-9391-6733558cd675.jpg)

This isn´t a minnor issue this is big one.

**Comment by PerseusAegis** [comment]
Well, nothing that completely breaks or crashes the game anyways lol.

Found another. Before & After...
 
![D64Switch2Before](https://user-images.githubusercontent.com/88910929/214442754-8c85293a-1019-4f8f-880b-0f11ff0782b6.jpg)
![D64Switch2After](https://user-images.githubusercontent.com/88910929/214442762-701ebdae-4c4a-4af8-8426-d9a31c443b81.jpg)

**Comment by Wolf3s** [comment]
[doom64ex-plus-3.6.5.4-windows.zip](https://github.com/atsb/Doom64EX-Plus/files/10494814/doom64ex-plus-3.6.5.4-windows.zip)
Try this build i´ve fixed this issue.

**Comment by PerseusAegis** [comment]
> [doom64ex-plus-3.6.5.4-windows.zip](https://github.com/atsb/Doom64EX-Plus/files/10494814/doom64ex-plus-3.6.5.4-windows.zip) Try this build i´ve fixed this issue.

Yep, seems to be fixed now. If I find any other issues, i'll report them. Much thanks again!

**Comment by Wolf3s** [comment]
> > [doom64ex-plus-3.6.5.4-windows.zip](https://github.com/atsb/Doom64EX-Plus/files/10494814/doom64ex-plus-3.6.5.4-windows.zip) Try this build i´ve fixed this issue.
> 
> Yep, seems to be fixed now. If I find any other issues, i'll report them. Much thanks again!

You are welcome :)

**Comment by atsb** [comment]
This was fixed in the hotfix a few hours ago.  I reverted some extra stuff by mistake

**Comment by atsb** [comment]
@wolfysdl did you also update the release?  Because I specifically fixed it already and would prefer if it wasn’t touched.

**Comment by Wolf3s** [comment]
> This was fixed in the hotfix a few hours ago. I reverted some extra stuff by mistake

In reality you just changed the actor function nothing less anyway i will update the sourceforge repo and then probablly i will merge my wolfy branch to main.
Update: i didn´t update the sourceforge after the sparta kick about the releases confusion that i caused.

**Comment by Wolf3s** [comment]
> @wolfysdl did you also update the release? Because I specifically fixed it already and would prefer if it wasn’t touched.

yes

**Comment by atsb** [comment]
Please do not update releases.  I’m going to re upload mine.

**Comment by Wolf3s** [comment]
> Please do not update releases. I’m going to re upload mine.

sorry man not updating on the next time!!!
