### ISSUE TITLE
Some sounds/sfx persist after source of said sfx is inactive...

### ISSUE THREAD

**Issue by PerseusAegis** [atsb/Doom64EX-Plus#164]
Had some sounds/sfx that are stuck continuously playing. The plasma rifle's idle electric crackle hum is one example. It continued to play after changing weapons, restarting the level with no plasma rifle, and even after exiting to the main menu. Only completely exiting and restarting the game solves this. Another sound did this, but I couldn't identify that sound.

Seemed to only happen in the second level of The Unmaking after encountering a large group of enemies. Maybe all those enemies making sounds at once causes this bug? Version 3.6.5.4.

**Comment by atsb** [comment]
Fixed in stable (as far as I have tested)
