### ISSUE TITLE
command line parameters

### ISSUE THREAD

**Issue by liPillON** [atsb/Doom64EX-Plus#176]
Hi, quick question: does EX+ support the same command line parameters as EX?
https://doom64ex.sourceforge.net/wiki/index.php/Command_Line_Parameters

In my tests it appears that "-config" has no effects.
The others I'm using (-width, -height, -iwad, -file) works as expected.

I'd like to keep separate cfg files (savefiles would be nice, too!) for each pwad I'm playing and so I've set up a bunch of cmd scripts:
- this would be the command line used for playing a pwad: `.\doom64ex-plus.exe -iwad .\DOOM64.WAD -file .\uncensored.wad .\maps\d64cp1.wad -config .\user\d64cp1.wad\doom64ex-plus.cfg -width 1920 -height 1200`
- this instead would be used when playing without pwads: `.\doom64ex-plus.exe -iwad .\DOOM64.WAD -file .\uncensored.wad -config .\user\doom64ex-plus.cfg -width 1920 -height 1200`

I've already checked that the required cfg files are correctly populated and placed in the designated directory

I'm using the 3.6.5.4 release binaries updated on february, 15th
The host OS is Win11 22H2 x64

Thank you for working on this port and for the time you would dedicate on this issue!

**Comment by atsb** [comment]
I will look into this

**Comment by atsb** [comment]
So I looked at this and while I got it to work, unfortunately, the way EX was made, if you choose an external config file, it will overwrite the defaults in the standard config file.  I'll have to do a bit of refactoring to stop this happening.
