### ISSUE TITLE
Game crashes to desktop upon opening

### ISSUE THREAD

**Issue by ks202005** [atsb/Doom64EX-Plus#180]
I have all the files required in the directory `I:\Games\Doom64EXPlus`, but trying to start the game from the launcher and by launching the executable manually results in the window opening for a split second and immediately closing. 

Switching to full screen doesn't solve the issue.

I can't find any way of logging errors either.

**Comment by ks202005** [comment]
This seems to require the DOOM64.WAD with the MD5 checksum `0aaba212339c72250f8a53a0a2b6189e` (which is used by the official 2020 release), whereas the DOOM64.WAD I had used with the original Doom 64 EX has a checksum of `e1f1c2bba2c1be41e22aa2e4d37d169e`. The files are different sizes, presumably because of the Lost Levels being added, but there should at least be a warning that either the official WAD is required when loading an incompatible WAD.

**Comment by atsb** [comment]
This is listed in the readme.  I suggest you read it, supporting the IWAD means no longer supporting the old EX ROM Dump.  This is also specified in the Mod section of the readme due to the different tags.
