### ISSUE TITLE
Video freezes when trying to re-enable interpolation if filter is set to nearest

### ISSUE THREAD

**Issue by ks202005** [atsb/Doom64EX-Plus#181]
Setting the filter option to "Nearest", then setting interpolation to "Off", then switching interpolation to "On" again freezes the video of the game until interpolation is disabled again. 

Setting the filter option back to Linear after freezing once does not mitigate the issue. 

Version: 3.6.5.4
OS: Windows 10 IoT Enterprise LTSC
GPU: AMD RX 580

Edit: I just found [this issue](https://github.com/atsb/Doom64EX-Plus/issues/145) that reports nearly the same issue, but I can't repeat having the problem without first switching to nearest neighbor filtering, and I'm using a newer version which should be partially patched against that issue.

**Comment by atsb** [comment]
Fixed in latest RC2
