### ISSUE TITLE
[Feature] Mouse controls for automap zoom

### ISSUE THREAD

**Issue by ks202005** [atsb/Doom64EX-Plus#183]
Currently, it seems you're unable to bind mouse buttons such as the Mouse 4 and Mouse 5 thumb buttons to zoom the automap in and out. Trying to bind the mouse wheel for zooming (a la PrBoom+) appears broken; I can only get it to zoom in, and it keeps zooming until the max zoom is reached.

**Comment by atsb** [comment]
The automap in D64 is pretty basic when compared to PrBoom etc..  scrolling the mousewheel will now still select the weapons from the weapon wheel.  The reason is that the automap is an overlay, it isn't a 'state' and so this will require a complete overhaul of the automap.

**Comment by atsb** [comment]
Decided won't do.
