### ISSUE TITLE
Segmentation Fault in the last build

### ISSUE THREAD

**Issue by orderorder** [atsb/Doom64EX-Plus#188]
GL_VENDOR: AMD
GL_RENDERER: OLAND (, LLVM 15.0.7, DRM 2.50, 6.1.19-1-MANJARO)
GL_VERSION: 4.5 (Compatibility Profile) Mesa 23.0.1
GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_TEXTURE_UNITS_ARB: 8
zsh: segmentation fault (core dumped)

I have an older build that doesn't show the segmentation fault on the same hardware

**Comment by MiscStuff839** [comment]
Same issue.

**Comment by atsb** [comment]
Thanks both, I'll give this a test on my Manjaro system.

**Comment by atsb** [comment]
Latest commit fixes it.  Adaptive vsync issue with calling glx.  Swapped it for SDL Interval code for Linux.

**Comment by muppi090909** [comment]
> Latest commit fixes it. Adaptive vsync issue with calling glx. Swapped it for SDL Interval code for Linux.

Can confirm.

@orderorder Has it fixed it for you as well ?

**Comment by MiscStuff839** [comment]
When I try to start a new game or load an old save I get the following Error 
![image](https://user-images.githubusercontent.com/79302850/229358344-c4746340-b8b6-44e1-b0bd-9458a05f8a47.png)

**Comment by atsb** [comment]
Are you using Stable or Master?  Because Master won't work.  This doesn't happen on my Manjaro system.

**Comment by orderorder** [comment]
Now it works well on my Manjaro system

**Comment by MiscStuff839** [comment]
> Are you using Stable or Master? Because Master won't work. This doesn't happen on my Manjaro system.

Switched to stable but there is a constant crackling sound in the background. I have never used a N64 but I am pretty sure that this is not supposed to happen.

**Comment by MiscStuff839** [comment]
Just tried downloading directly from the github repo and it works somehow. Thanks !

**Comment by atsb** [comment]
> 

Fluidsynth, the default is alsa which can be crackly.  I'll default it to pulseaudio which doesn't have that issue.

**Comment by MiscStuff839** [comment]
Well, it is fixed once I switched to pipewire.
