### ISSUE TITLE
[Feature] Disable quick save/load prompts

### ISSUE THREAD

**Issue by ks202005** [atsb/Doom64EX-Plus#192]
Currently, there's a prompt asking you if you're sure you want to overwrite your quick save file or load your quick load file. 

I understand the desire for a safety mechanism to prevent accidental overwriting and loading, but generally quick saving and loading is immediate, hence "quick". I feel that as it stands, there's not much reason to use the quick save/load functionality because it's not that much faster than the F2/F3 save/load menus (2 key presses instead of 3). 

An option to disable these prompts would be welcome.

**Comment by atsb** [comment]
Good idea, lets just make it like DSDA where it is an instantaneous loading of the quicksave

**Comment by atsb** [comment]
This is now done in the latest 2 commits.  I'll do a release in the next few days with this included.
