### ISSUE TITLE
[Bug] "Decoy" soldier in Level 21: Pitfalls

### ISSUE THREAD

**Issue by ks202005** [atsb/Doom64EX-Plus#194]
In Level 21: Pitfalls, I reached a location where there a soldier has a lifeless double that spawns in the same location. 

[Doom 64 EX Plus Level 21 decoy soldier bug.webm](https://user-images.githubusercontent.com/65844375/230342741-452739f0-dd9e-4d3e-bccd-a74ff9f6b99a.webm)

![sshot008](https://user-images.githubusercontent.com/65844375/230342791-542bb320-52fe-4f93-b326-0463194cc1dc.png)
![sshot013](https://user-images.githubusercontent.com/65844375/230342804-7a3aed35-fab0-407d-aaae-169118909144.png)

**Comment by atsb** [comment]
This is a vanilla bug that is also in the remaster.  It would also happen on the N64 too.

**Comment by ks202005** [comment]
Ah, didn't know that. I've only played through Doom 64 through Absolution. That's interesting!

**Comment by atsb** [comment]
> Ah, didn't know that. I've only played through Doom 64 through Absolution. That's interesting!

I am trying to figure out what causes it.  There really isn't any set 'thing' that makes it do this so it is one of those elusive issues that will take a while to figure out.

**Comment by ks202005** [comment]
I presume it has something to do with the fact that the data from the IWAD is derived from the N64 ROM? It's really amusing to me that a bug like that could be carried over in such a way; it's so unexpected that I didn't even consider it when writing this issue.

**Comment by atsb** [comment]
I took a lot of code from the reverse engineered DOOM64-RE project so some parts of EX+ are extremely vanilla while other parts are not.  :)
