### ISSUE TITLE
[Bug] Gameplay demos broken

### ISSUE THREAD

**Issue by ghost** [atsb/Doom64EX-Plus#195]
Hi, I have noticed that the gameplay demos after the intro sequence are broken. For example, the first "Main Engineering" stage demo, the player will proceed to run to the corner ahead and to the right, in the starting area, and they will never escape. The subsequent two demo sequences have the player constantly looking up and spinning. 

I thought this might have something to do with "Mouse Look" being enabled, but turning off "Mouse Look" and restarting the game made no difference.

I compiled from a repo clone dated 15 April '23.

**Comment by atsb** [comment]
Not a bug just an unfinished attempt.  EX never played the original demos as it was (and EX+ still is) incompatible with them due to the vanilla inaccuracy of some game logic.  I took code from DOOM64-RE for initial implementation but never finished the vanilla stuff

**Comment by ghost** [comment]
Oh, cool! Thanks for clarifying. I'll close this, then, since it's not a bug. :D

**Comment by atsb** [comment]
One day I will finish it
