### ISSUE TITLE
Inconsistent scaling of screen elements

### ISSUE THREAD

**Issue by owner-w** [atsb/Doom64EX-Plus#197]
Screen messages are scaled inconsistently with the rest of the hud. They appear much smaller than they should be, if you compare them to the original game. They also seem positioned more to the top left of the screen, when they should have larger margins.

![Base Profile Screenshot 2023 04 28 - 15 53 23 93](https://user-images.githubusercontent.com/132102644/235252361-b6a2f3bc-d2ed-41fc-8253-2952afc4c71d.png)

Regular EX does not have this issue:

![Base Profile Screenshot 2023 04 28 - 15 53 39 93](https://user-images.githubusercontent.com/132102644/235252387-7a357f79-7bfb-499a-9597-c5c2711719bd.png)

**Comment by atsb** [comment]
This is designed so that the always on hud stats can fit next to them.  I reduced the screen text by about 30% for this

**Comment by owner-w** [comment]
Can it be made a toggle? Maintaining the original look is more important than showing stats that are accessible from the automap anyway.

**Comment by azamorapl** [comment]
Sorry, I deleted the last comment by accident, I meant to reply saying that the text scaling can be made conditional: #199

**Comment by atsb** [comment]
It can be but I decided it would be very jarring for those who like to occasionally change settings, so I left it as this so there is one look.  It’s perfectly readable on my 2k screen so I’m not gonna change it.

**Comment by atsb** [comment]
> Sorry, I deleted the last comment by accident, I meant to reply saying that the text scaling can be made conditional: #199

Oh I saw the PR.  I initially thought it would be very jarring for users who like to change settings as the text would be small then huge.  But I guess it could work.

**Comment by atsb** [comment]
Ooops @azamorapl - looks like the PR broke the game :D 'episode' is no longer recognised and causes a startup failure

**Comment by azamorapl** [comment]
Strange, I can't reproduce it, it works fine on my end. I tried a clean build of stable and the PR branch. I'll investigate more...

![Base Profile Screenshot 2023 04 29 - 07 30 41 15](https://user-images.githubusercontent.com/12489485/235302670-79d8dcba-47a2-4344-92f2-5374a72ee367.png)

**Comment by atsb** [comment]
I only tried it on Linux, maybe it works fine on windows because the commit before yours works ok
