### ISSUE TITLE
64bit clean

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#2]
Certain parts of the code aren't 64bit clean and will causes issues with tag activations and level warping/exiting if compiled as a 64bit binary.  I've done a lot of fixing for this, but there is still much to do.

**Comment by atsb** [comment]
Level warping is now ok.  However, on 64bit executables, shooting secrets like on MAP22 do not function.  No idea why, I've gone over that code countless times, but the game is indeed playable.  Once these issues are worked out, I'll start providing x64 builds too.

**Comment by bfg01** [comment]
Does this mean that, on Linux x64, I will never be able to get all secrets in MAP22 because of this ever-existing bug?

**Comment by atsb** [comment]
Correct.  I haven’t found out why the macro isn’t executed on 64bit…. Yet

**Comment by atsb** [comment]
You can of course use idclip to get it

**Comment by atsb** [comment]
This is done
