### ISSUE TITLE
Error - W_Init: IWAD not found

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#20]
Git-cloned today; finally built.

But now, when running, having put DOOM64.wad in corresponding place beforehand, I only get this:
```
Z_Init: Init Zone Memory Allocator
CON_Init: Init Game Console
G_Init: Setting up game input and commands
M_LoadDefaults: Loading game configuration
I_Init: Setting up machine state.
D_Init: Init DOOM parameters
W_Init: Init WADfiles.
Error - W_Init: IWAD not found

********* ERROR *********
W_Init: IWAD not found
```

I already tried putting **all** files, including the binary, in:
$XDG_DATA_HOME/doom64ex-plus
The directory DOOM64EX-Plus binary was built
Other directories

I also checked the checksum for the DOOM64.wad, and is correct.

What could be happening here?
Thanks again.

**Comment by atsb** [comment]
And it is DOOM64.WAD right, in all caps?

I know the issue...

**Comment by atsb** [comment]
I just pushed a fix.  I forgot that I never changed the doom64.wad line in w_file.c (the N64 dump had it in lower-case).  The Remaster has DOOM64.WAD in all caps.  I changed mine locally to lower-case and never got the issue.

I have now put this into all caps to match the remaster IWAD.  Windows never had this issue as it does not care about case, it is case-insensitive.

**Comment by bfg01** [comment]
Just for the notes, yes, it was DOOM64.WAD in all caps. But I guess I still needed to do more tests with renaming...

Thanks again.
