### ISSUE TITLE
Add versioning to the Windows executable

### ISSUE THREAD

**Issue by SumatraPeter** [atsb/Doom64EX-Plus#202]
Would be nice if the Windows EXE had a file description, version etc. added to it (see the GZDoom EXE for example, or pretty much any program really).

**Comment by Wolf3s** [comment]
> Would be nice if the Windows EXE had a file description, version etc. added to it (see the GZDoom EXE for example, or pretty much any program really).

Sounds nice.

**Comment by atsb** [comment]
![image](https://github.com/atsb/Doom64EX-Plus/assets/44937323/de1098c9-2b48-4251-ab2f-40ef35b6ee56)

Will be in the next release
