### ISSUE TITLE
Sometimes sound disappears

### ISSUE THREAD

**Issue by bubbleguuum** [atsb/Doom64EX-Plus#203]
Using RC2.

I'm playing the Lost Levels and sometimes sounds entirely disappear (while music still plays).
It seems to happen only in heavy fights with lots of monsters.
It happens very quickly on the final map of the 'Lost Levels'.
When this issue happens, only restarting the game fixes it.

**Comment by atsb** [comment]
Is this using the latest RC2?  Because I reverted the SDL2 change that caused this and it is back to how it was.  The latest was added yesterday.

**Comment by bubbleguuum** [comment]
I am using the RC2 zip that you posted on the "Choppy frame rate" issue 2 days ago.

**Comment by atsb** [comment]
So it would be fixed by now then.  That RC2 is outdated now.

**Comment by bubbleguuum** [comment]
Understood !
