### ISSUE TITLE
Linux build.sh Compile Error

### ISSUE THREAD

**Issue by d10sfan** [atsb/Doom64EX-Plus#204]
On the latest, receiving the following error when trying to use build.sh.

```
gcc: error: gl_shader.c: No such file or directory
```

It looks like this is because those files were removed in this commit: https://github.com/atsb/Doom64EX-Plus/commit/83cbb6123615d94fb7f6816d03736e330ba25ab6#diff-77f81659bbc3a02f1113600340e6b1e7be0de9281976ed3ec5a1e10296ca4fc4

**Comment by d10sfan** [comment]
The new makefile has the same problem

**Comment by atsb** [comment]
It’s a 5 second fix by simply removing this from the makefile.  I forgot to remove this and I’ll commit a fix later

**Comment by atsb** [comment]
Just pushed a fix

**Comment by d10sfan** [comment]
Thanks, that did the trick! Wasn't sure if that file was expected but missing
