### ISSUE TITLE
W11 Windows Defender detects DOOM64EX+.exe v3.6.5.8 as infected with Trojan:Win32/Wacatac.B!ml (false positive)

### ISSUE THREAD

**Issue by bubbleguuum** [atsb/Doom64EX-Plus#205]
As the title says. Of course it is a false positive (Virus Total does not detect it), which seems to not be uncommon with executable compiled with Visual Studio.
The problem is that is removes the file automatically and it requires some extra steps for it to not do so.
Interestiongly, I could run the executable a few times before it made that detection.

**Comment by atsb** [comment]
Weird, it’s compiled using the W11 SDK even..  no idea what could be different about it.
