### ISSUE TITLE
Gamepad support for Steam Deck

### ISSUE THREAD

**Issue by EmperorPenguin18** [atsb/Doom64EX-Plus#208]
I know that I can just use gamepad to mouse mapping, but I would prefer native controller bindings. I think this may have already been implemented with https://github.com/atsb/Doom64EX-Plus/pull/124 but it's not working for me on the latest release.

**Comment by Shockwave508** [comment]
As a fellow Steam Deck user, a fix would most-definitely be appreciated, especially with how easily Doom 64 EX+ can be applied through Luxtorpeda.

**Comment by atsb** [comment]
Gamepad support was attempted but we could never get it to work properly and the effort was abandoned as neither Myself nor the other programmers knew the GameController API well enough to get it working.  I'd still merge it if anyone managed to do it in the future.

EX+ was indeed made to work out of the box on Linux and the Deck especially.  This is kinda the last thing that isn't well suited to it.

**Comment by blackhand1001** [comment]
Strangely the most recent Doom64Ex build does in fact have controller support. I wonder if its something that could be ported over to this.

**Comment by atsb** [comment]
> Strangely the most recent Doom64Ex build does in fact have controller support. I wonder if its something that could be ported over to this.

It is only controller support for Windows using ancient xinput features.  It isn't a cross-platform implementation.  SDL2 Game Controller support is what is needed, especially for Linux.

**Comment by atsb** [comment]
Someone else can implement this, but I won't.  I've tried many times and it just is not worth my time to do it.  More contributors would definitely help with the feature requests, but right now, with just myself, it isn't something I will spend a lot of time on.  I've written and rewritten the controller code 4 times to try and get gamepad support with SDL2 working, but never had much success.
