### ISSUE TITLE
Bloated 3.6.5.8 Launcher requires new .NET version?

### ISSUE THREAD

**Issue by SumatraPeter** [atsb/Doom64EX-Plus#219]
Edit: Looks like a complaint against MS' .NET 4.x vs 6.x bloat touched a nerve with the dev, so forget it. For the record, yes, a 20 MB vs 30 KB (previous version) simple Launcher app is most _definitely_ a perfect example of bloat. Whether or not people have 20 MB free HDD space in this day and age is immaterial. User resources aren't there to be wasted unnecessarily by MS or other app devs who cannot optimize code worth a damn and use easy resource availability as an excuse.

**Comment by atsb** [comment]
If you think it is bloat, then you have no idea what you're talking about.  The new launcher is written in .NET6.0 not the older .NET5 or 4.  Your system doesn't have .NET6.0 installed.

Yes, it has changed a lot and that is not my fault, but rather how .NET6 now packages itself.  I'm sure you have 20MB of space left.

If you don't like it, don't use it.
