### ISSUE TITLE
Secret items wrongly counted after loading game

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#234]
Basically on release 3.6.5.9 from October 22 this very same bug #38 is back; also tested in very same level you tested back then: MAP29 Outpost Omega.
See comment https://github.com/atsb/Doom64EX-Plus/issues/38#issuecomment-1357086969

Is this a regression?

**Comment by atsb** [comment]
This is highly likely an SDL3 issue where many things were converted from ints to floats in order to support it (SDL3 deals in floats for many things now) and so this likely isn't working well.  I'll take a look at the commit I did to fix it and fix it again :)

**Comment by bfg01** [comment]
Just to clarify in case I was not able to, when saying "October 22" I meant the non-SDL3 build.

**Comment by atsb** [comment]
Hmmmmm, I'll have to look at the backporting I was doing at the time and see what I've broken.
