### ISSUE TITLE
Bug in starting room of MAP08 Final Outpost

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#235]
Not sure if an intended behavior...
After killing the initial enemies one needs to step into the only light in the floor being off to activate the lift out, but this lift activates only once; if failing to ride it it never gets activated again despite stepping on the same light off.

Intended, or bug?

**Comment by atsb** [comment]
I don't quite remember if this is vanilla behaviour or not, I will check the remaster and see if its the same

**Comment by bfg01** [comment]
Would it be possible to also check original Doom 64 on N64?

**Comment by atsb** [comment]
I could use an emulator and a password for the level I guess, but remaster is easier and is confirmed as vanilla compatible.

**Comment by PerseusAegis** [comment]
Unfortunately, this is still an issue with the version 4.0.0.0 release.

**Comment by atsb** [comment]
Yeah it is, I'll probably take a look at it soon.  It is likely a bug in the line crossing for this type of linedef action

**Comment by atsb** [comment]
I've confirmed it is a bug in EX+ but I'm not sure exactly where.  I'll have to dig into this.

**Comment by bfg01** [comment]
Does this mean this issue certainly does not happen in Remaster or original N64?

**Comment by PerseusAegis** [comment]
> Does this mean this issue certainly does not happen in Remaster or original N64?

I tested Remaster and N64 versions as well, and it does not happen in either of those.

**Comment by atsb** [comment]
> Does this mean this issue certainly does not happen in Remaster or original N64?

Correct

**Comment by atsb** [comment]
I'll look at this today

**Comment by atsb** [comment]
So it seems somewhere, I'm now allowing these 'fake items' to be picked up, which means it only gets triggered once because the second time, there is no fake item to run over.  I'll have to check a few areas and see where I messed up.

**Comment by atsb** [comment]
Fixed
