### ISSUE TITLE
Getting constant jittering when playing on latest versions

### ISSUE THREAD

**Issue by elhroberts56** [atsb/Doom64EX-Plus#236]
I am running Doom64EX-Plus on the latest version of Windows 10 at 144 fps. With both versions 3.6.5.8 and 3.6.5.9, I am getting constant jittering and micro-stuttering while playing the game. It's noticeable whenever I move around. It gets worse when I try to cap the frame rate at 90 or below, and forcing vsync via Nvidia options doesn't help.

**Comment by atsb** [comment]
Don't force vsync on nvidia settings.  Rather, for this game, tell nvidia settings to not set any vsync at all.  Nvidia cards cause stuttering

**Comment by elhroberts56** [comment]
Alright, I forced vsync off from Nvidia control panel and now the game seems to run buttery smooth. Thank you very much! Do you think you could add this to the main page and readme so that other people using Nvidia cards can solve this issue as well?
