### ISSUE TITLE
DOOM64EX+ Launcher doesn't appear to work

### ISSUE THREAD

**Issue by elhroberts56** [atsb/Doom64EX-Plus#237]
Whenever I try to start the DOOM64EX+ Launcher.exe, it doesn't do anything at all, no popup window or anything. Only the regular DOOM64EX+.exe starts the game. I do have all three required files in the same directory as the executables.

**Comment by atsb** [comment]
Do you have .net 6+ installed?

**Comment by elhroberts56** [comment]
Ok, I only had the .net sdk's installed. I just installed the .net 6.0.26 desktop runtime and now the launcher works. Thanks! Perhaps this should be mentioned on the main page though, I don't believe I ever saw anything about .net mentioned in the readme.

**Comment by atsb** [comment]
Done.
