### ISSUE TITLE
I have Hectic rewards without finishing it

### ISSUE THREAD

**Issue by Alerymin** [atsb/Doom64EX-Plus#238]
The game comes with the features menu and hardcore difficulty enabled by default while I did not finish Hectic. is this normal ? and can this be disabled ?

**Comment by atsb** [comment]
> The game comes with the features menu and hardcore difficulty enabled by default while I did not finish Hectic. is this normal ? and can this be disabled ?

This is designed that way.  I removed the disabling because if people want to just have fun and go nuts, I want them to have that flexibility of doing so.

**Comment by Alerymin** [comment]
ok I see
