### ISSUE TITLE
Gamma is blown out.

### ISSUE THREAD

**Issue by StrikerTheHedgefox** [atsb/Doom64EX-Plus#239]
Seems in the latest release, the gamma is completely blown out and everything is too bright and washed-out.

**Comment by atsb** [comment]
You can adjust gamma in the settings menu as well as the gamma control keys.

**Comment by StrikerTheHedgefox** [comment]
Adjusting the gamma had no effect when I reported this. Is this something new?

**Comment by atsb** [comment]
It was due to integer vs floats on SDL3, I had it committed but it wasn't in the release.
