### ISSUE TITLE
Anisotropy Needs Mip Maps to be generated. 

### ISSUE THREAD

**Issue by blackhand1001** [atsb/Doom64EX-Plus#248]
On NVIDIA cards the driver will automatically create mip maps if anisotropy is enabled and mip maps don't exist in the current texture object. This is actually non-standard behavior. On every other type of GPU it needs to be manually done by calling the function in OpenGL to create them. 

It should be a relatively easy fix. This just needs to be added in the appropriate spot. 

https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGenerateMipmap.xhtml

**Comment by atsb** [comment]
I'd rather just disable anisotropy in that case.  I don't have NVidia cards and refuse to use them, so it doesn't bother me either way.

**Comment by blackhand1001** [comment]
I think you misunderstood. It only works on NVIDIA cards. It however makes a huge difference in image quality. That difference can easily be possible on all gpus with a single line of code.

**Comment by atsb** [comment]
In that case I will add it, thanks

**Comment by atsb** [comment]
> I think you misunderstood. It only works on NVIDIA cards. It however makes a huge difference in image quality. That difference can easily be possible on all gpus with a single line of code.

So what I've gathered is that you must add this to each part of the code that generates a texture.  Therefore it isn't just 'one line of code' but rather a copy/paste in about 25 areas.  I'll see if there is a nicer way to do this as I hate duplicating.

**Comment by atsb** [comment]
Decided won't do.  It isn't a clean implementation of this, especially considering how the rendering is.
