### ISSUE TITLE
Sounds Section not found in IWAD

### ISSUE THREAD

**Issue by ChexWarrior** [atsb/Doom64EX-Plus#25]
Hello,

Compiled from latest master just an hour ago (Ubuntu) and when attempting to run the DOOM64EX-Plus I get this output:
```
$ ./DOOM64EX-Plus 
Z_Init: Init Zone Memory Allocator
CON_Init: Init Game Console
G_Init: Setting up game input and commands
M_LoadDefaults: Loading game configuration
WARNING: Unknown Key
I_Init: Setting up machine state.
D_Init: Init DOOM parameters
W_Init: Init WADfiles.
W_AddFile: Adding /home/andy/Desktop/Doom64EX-Plus/src/engine/doom64ex-plus.wad
Error - Sounds section not found in IWAD

********* ERROR *********
Sounds section not found in IWAD%            
```

Is this an issue with the DOOM64.WAD itself? I generated it using the old Doom64Ex executable with -wadgen on the game rom.

Thank you

**Comment by thekovic** [comment]
The WAD generated from the ROM is not supported in EX+, use the IWAD from Nightdive's remaster.

**Comment by ChexWarrior** [comment]
Okay thank you
