### ISSUE TITLE
Possible bug in MAP16 Blood Keep?

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#250]
Actually not sure if it's really a bug or original behavior from N64...

I notice that there's no monster infighting at all in this whole level. Is this by design?

Thanks.

**Comment by atsb** [comment]
![no_infighting](https://github.com/user-attachments/assets/72ca3237-c725-4b52-9ec1-07a061f30e09)

MAP16 has no infighting for all mobs.  Confirmed from extracted MAP16 from the iwad and checked in DB64.
