### ISSUE TITLE
crashlog needed

### ISSUE THREAD

**Issue by CaptainRobi** [atsb/Doom64EX-Plus#252]
The exe lacks any means to dump errors into a crashlog as the .exe is refusing to start and without means to show the errors that are causing it.

**Comment by Wolf3s** [comment]
There´s a command line for that.

**Comment by CaptainRobi** [comment]
How do I go around doing that?

**Comment by Wolf3s** [comment]
You need to deactivate the full screen mode.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by atsb** [comment]
If it is crashing on startup, the only way this would happen is if you lack the wadfile, the IWAD or the soundfonts.  If you follow the instructions for setup, it won't.
