### ISSUE TITLE
HUD Stats Not Working

### ISSUE THREAD

**Issue by StroggVorbis** [atsb/Doom64EX-Plus#253]
As of the latest release [4.0.0.0], the HUD stats stopped working,
specifically Kills, Items and Secrets always showing 0/0,
doesn't make a difference whether it's the automap only stats or the always on stats.
![image](https://github.com/user-attachments/assets/a9b3abce-8150-4837-9352-efd2f22f719d)

**Comment by atsb** [comment]
https://github.com/atsb/Doom64EX-Plus/commit/2fc357e179af3ff808c87e10268cb2767a10e8cf

This fixes it

**Comment by atsb** [comment]
I will do a new release soon with these included

**Comment by atsb** [comment]
Release is updated and built from the latest master
