### ISSUE TITLE
Crusher speed is not the same as the steam release. 

### ISSUE THREAD

**Issue by JamesC0222** [atsb/Doom64EX-Plus#254]
Fast crushers behave differently than the steam release, as shown in the videos below. Crushers in EX-plus move significantly slower. 

https://github.com/user-attachments/assets/5f06b749-573c-40ab-89e0-72fbea0d6915

https://github.com/user-attachments/assets/11986657-bcb7-408f-85b1-04e9e8597de2

**Comment by atsb** [comment]
I'll fix this ASAP
