### ISSUE TITLE
Just some questions from a noob

### ISSUE THREAD

**Issue by SilentMRG** [atsb/Doom64EX-Plus#260]
Hello everyone!

Today I discovered this incredible source port, friendly with potatoes, so I needed to test it, and I saw that to run the assets this is necessary: 

- DOOM64.wad
- doom64ex-plus.wad
- doomsnd.sf2

Well, the last two files are already in the source port, so when in doubt, I added these files from my GOG version:

- DOOM64.WAD
- DOOMSND.DLS
- Doom64.kpf

Are DOOMSND.DLS and Doom64.kpf necessary or not?

Why are doom64ex-plus.wad and doomsnd.sf2 listed as required if they are already on the source port?

And what is "DOOM64_ALPHA.wad" be in the "official_pwads" directory? I loaded DOOM64.WAD outside the "official_pwads" directory, but with "DOOM64_ALPHA.wad" inside, so I don't know whether or not this could cause any errors or change anything in the game.

Thank you in advance for your attention... And thank you for creating this project! Best regards! =)

**Comment by Wolf3s** [comment]
These guys are from the re release version which is using kex engine in C++. If kaiser re-release the doom64ex source code again along with the kex engine then yes doom64ex-plus will support loading these files.

DOOM64.WAD
DOOMSND.DLS
Doom64.kpf

**Comment by SilentMRG** [comment]
Thank you my man!

But I think you mean it will support these files...

DOOMSND.DLS
Doom64.kpf

Because DOOM64.WAD is supported by the source port.

I was told that "DOOM64_ALPHA.wad" is a mod, what exactly does it do with DOOM64.WAD? I tried running with it and without it and didn't see any difference.

**Comment by atsb** [comment]
These two files are not required and are not used by EX+

Use the Alpha wad as a pwad against DOOM64.WAD (-file <alpha wad>).

The two files listed as required that are already included, is because people in the past, forgot to add them to their directory and then complained it doesn't work..

**Comment by SilentMRG** [comment]
> These two files are not required and are not used by EX+
> 
> Use the Alpha wad as a pwad against DOOM64.WAD (-file ).
> 
> The two files listed as required that are already included, is because people in the past, forgot to add them to their directory and then complained it doesn't work..

Thanks for the clarifications, mate!
