### ISSUE TITLE
Feature REQUEST for 21:9 resolutions

### ISSUE THREAD

**Issue by Darkstalix** [atsb/Doom64EX-Plus#261]
Hey is it possible to add 3440x1440 for 21:9 resolution?
Also the Reloaded is not working on this beautiful port anymore?

Thanks in advance

**Comment by atsb** [comment]
Reloaded isn't officially supported and Atomic doesn't want numerous versions floating around until the transparent textures are implemented and one wad can be used on both.  Won't be happening soon unless you 'personally' edit the wad yourself without sharing it, and make it run on EX+.

I can add 21:9 resolutions yes.

**Comment by Darkstalix** [comment]
I wish I knew what you mean about the transparency tho, is there a thread about this so i wont bother you any further?
I could do some editing cause ive done alot in the past no problem.

Anyway thanks a lot for the resolution implementation

**Comment by atsb** [comment]
For example, in the first map, there is the laser barrier.  On the remaster, the laser textures are transparent, on EX+, they are solid.

**Comment by Darkstalix** [comment]
understood, thanks for the info

**Comment by Lobocop32x** [comment]
3440x1440 would makes this amazing :D
