### ISSUE TITLE
Crash with lost souls

### ISSUE THREAD

**Issue by StevenSYS** [atsb/Doom64EX-Plus#263]
A lot of the time when I'm fighting lost souls I get a crash with this error: `Error - Z_Touch: touched a pointer without ZONEID (src/engine/p_mobj.c:113)`

OS: Arch Linux

https://github.com/user-attachments/assets/573c6063-90b6-48f6-86fc-9ef46251585e

https://github.com/user-attachments/assets/262d8628-563d-4172-a02d-e3df178f1749

**Comment by atsb** [comment]
Hmmmmm

I'll take a look at this later, thanks!

**Comment by StevenSYS** [comment]
Here's some (hopefully) useful info for you, I added `printf("block->id: %i\nZONEID: %i\n",block->id,ZONEID);` to line 425 in the `z_zone.c` file and here's the output before and when the game crashes:

![Screenshot from 2024-08-23 21-47-21](https://github.com/user-attachments/assets/16db28ce-a6f5-4e5d-83aa-414b2de5034b)

**Comment by atsb** [comment]
[DOOM64EX+.zip](https://github.com/user-attachments/files/16735605/DOOM64EX%2B.zip)

Hey, thanks for that.  Yep, I got it.  Looks like there were stale pointers being fed to the Z Memory Allocation and caused crashes when the pointer essentially didn't have any memory allocated to it.

I've implemented a new memory allocation algorithm and that will check for this as well as improved Z_Touch and P_SetTarget to conform to this new rule.  The attached binary contains the fix.

Let me know if it helps and I'll push the code for a hotfix.

**Comment by StevenSYS** [comment]
Thanks, I'm going to try it now to see if it works!

**Comment by StevenSYS** [comment]
I can't test it because it's for Windows.

**Comment by StevenSYS** [comment]
It seems to work perfectly!
