### ISSUE TITLE
Any chance of proper multiplayer support?

### ISSUE THREAD

**Issue by Ohthatguy43** [atsb/Doom64EX-Plus#265]
Hi! I have been trying to get multiplayer working on this with a friend for a couple of hours now, but whenever i'm hosting it seems like the game doesn't really host at all? even if i set everything correctly on my router, the game does not host at all. Very sorry if this was a bit messy, i'm really tired lol.

**Comment by atsb** [comment]
Never.  I don't do netcode and I'm not a netcode engineer.
