### ISSUE TITLE
[Just a note] Area 51 (2005) 

### ISSUE THREAD

**Issue by SilentMRG** [atsb/Doom64EX-Plus#268]
Hello everybody!

I just want to let you know that the source code is available here: https://github.com/ProjectDreamland/area51

And it's important to remember that the game in question is Freeware, and free of copyright since 2008, so if any programmer is interested in starting a source port project now is a good time, and there will be no barriers to it.

Cheers!

**Comment by atsb** [comment]
Oooo thanks!  I'm going to take a look at this!

**Comment by Wolf3s** [comment]
> Hello everybody!
> 
> I just want to let you know that the source code is available here: https://github.com/ProjectDreamland/area51
> 
> And it's important to remember that the game in question is Freeware, and free of copyright since 2008, so if any programmer is interested in starting a source port project now is a good time, and there will be no barriers to it.
> 
> Cheers!

Can do, But i would more focusing on multi-platform

**Comment by atsb** [comment]
I've taken a look and it seems the source is missing a lot of things.

The A51.dll file is nowhere to be found in the buildable code, neither are two other dll files that are in vanilla.

It seems the code is only to build the game binary.  I've gone back to the original source release but still, when fixed, it opens the window and bails out immediately.  We can debug it, but that is assuming it is fixable..  it could very well be a half-complete source archive.  It will take more time to discuss and analyse.

**Comment by SilentMRG** [comment]
> Oooo thanks! I'm going to take a look at this!

You're welcome! =)

> Can do, But i would more focusing on multi-platform

If the idea is to make it multiplatform, then I suggest that in Windows it is compatible with most backends and their versions, I mean, have support for D3D 9, 10, 11 and if possible OpenGL 2.1 and so on... Make it run on high-end PC and even on potatoes over 10 years old, hehe.

> I've taken a look and it seems the source is missing a lot of things.
> 
> The A51.dll file is nowhere to be found in the buildable code, neither are two other dll files that are in vanilla.
> 
> It seems the code is only to build the game binary. I've gone back to the original source release but still, when fixed, it opens the window and bails out immediately. We can debug it, but that is assuming it is fixable.. it could very well be a half-complete source archive. It will take more time to discuss and analyse.

I assume you took a look at this too: https://github.com/ProjectDreamland

As you can see the vanilla game assets are in a separate repository (game), as well as decompiled code in "research". I'm not a programmer, but I think that's it.

The vanilla version runs on D3D 9, uses Miles Sound System for audio, Bink Video for cut scenes and GameSpy (I don't think that exists anymore) for multiplayer.

The known problems of the vanilla version are black and missing textures in some parts of the game and an infernal stuttering in the cut scenes between missions, and this stuttering is so infernal that the solutions to solve it only mitigate it slightly, they don't actually solve it, because It probably must be a problem with the code, and how current Windows handles it. Apparently, the "Dreamland" project has the same problems and some minor ones.

I hope this information helps in some way. :)

**Comment by Wolf3s** [comment]
> > Oooo thanks! I'm going to take a look at this!
> 
> You're welcome! =)
> 
> > Can do, But i would more focusing on multi-platform
> 
> If the idea is to make it multiplatform, then I suggest that in Windows it is compatible with most backends and their versions, I mean, have support for D3D 9, 10, 11 and if possible OpenGL 2.1 and so on... Make it run on high-end PC and even on potatoes over 10 years old, hehe.
> 
> > I've taken a look and it seems the source is missing a lot of things.
> > The A51.dll file is nowhere to be found in the buildable code, neither are two other dll files that are in vanilla.
> > It seems the code is only to build the game binary. I've gone back to the original source release but still, when fixed, it opens the window and bails out immediately. We can debug it, but that is assuming it is fixable.. it could very well be a half-complete source archive. It will take more time to discuss and analyse.
> 
> I assume you took a look at this too: https://github.com/ProjectDreamland
> 
> As you can see the vanilla game assets are in a separate repository (game), as well as decompiled code in "research". I'm not a programmer, but I think that's it.
> 
> The vanilla version runs on D3D 9, uses Miles Sound System for audio, Bink Video for cut scenes and GameSpy (I don't think that exists anymore) for multiplayer.
> 
> The known problems of the vanilla version are black and missing textures in some parts of the game and an infernal stuttering in the cut scenes between missions, and this stuttering is so infernal that the solutions to solve it only mitigate it slightly, they don't actually solve it, because It probably must be a problem with the code, and how current Windows handles it. Apparently, the "Dreamland" project has the same problems and some minor ones.
> 
> I hope this information helps in some way. :)

Also i would see the consoles as well @atsb will possibly focus in modernization in latest C++ and other stuff while me i will take this path however i would keep legacy support to C++98 to 23 to keep the consoles supports.

**Comment by SilentMRG** [comment]
This has nothing to do with the topic at hand, but this whole source code thing reminded me of this: https://glampert.com/2015/09-01/reverse-engineering-darkstone/

"9 thousand years ago a warrior" tried to decompile the code of this classic ARPG on PC/PS1. I don't understand the subject, but it seems he made some progress and presented interesting things.

There's a discussion here about all this: https://rpgcodex.net/forums/threads/help-wanted-darkstone-evil-reigns-master-thread-help-patching-and-modding.133402/

Just a curiosity! I hope atsb doesn't have a heart attack after seeing this. XD

**Comment by Wolf3s** [comment]
> This has nothing to do with the topic at hand, but this whole source code thing reminded me of this: https://glampert.com/2015/09-01/reverse-engineering-darkstone/
> 
> "9 thousand years ago a warrior" tried to decompile the code of this classic ARPG on PC/PS1. I don't understand the subject, but it seems he made some progress and presented interesting things.
> 
> There's a discussion here about all this: https://rpgcodex.net/forums/threads/help-wanted-darkstone-evil-reigns-master-thread-help-patching-and-modding.133402/
> 
> Just a curiosity! I hope atsb doesn't have a heart attack after seeing this. XD

This Guilherme lampert is my inspiration on gamedev
