### ISSUE TITLE
Doesn't compile (Arch Linux)

### ISSUE THREAD

**Issue by StevenSYS** [atsb/Doom64EX-Plus#269]
It won't compile on Arch Linux, I haven't tried compiling it on any other OS though.

Latest commit:
![CompileError](https://github.com/user-attachments/assets/745596fa-59dd-4f67-ad83-82ddcda3bd5a)

Latest commit with the `#ifdef _WIN32` + `#endif` from `#ifdef _WIN32 #include "i_xinput.h" #endif` in `m_menu.c` removed:

![CompileError2](https://github.com/user-attachments/assets/f31156cb-63fd-4c81-b33c-ddbc6e2a63f1)

**Comment by bubbleguuum** [comment]
That's because bleeding edge SDL3 is needed. The last official public version of SDL3 is the 3.1.2, which is a few months old and too old for Doom64EX-Plus to compile with it. So we have to wait for a newer official SDL3 version to be released and be packaging in the distro. I have actually the same issue packaging  Doom64EX-Plus for openSUSE Tumbleweed and will have to wait.

**Comment by StevenSYS** [comment]
I am using bleeding edge SDL3.

**Comment by bubbleguuum** [comment]
First issue is due to this in `m_menu.c`:

```
#ifdef _WIN32
#include "i_xinput.h"
#endif
```

It compiles when removing the `#ifdef`

The `SDL_WaitSemaphore` issue is caused by not using the expected SDL3 version by the code (yours is too recent!). 
In up to date version this function is `void`:

https://wiki.libsdl.org/SDL3/SDL_WaitSemaphore

Until SDL3 is stable (or there is a new official preview release used by this project), there is bound to be such issues on Linux if not compiling with the SDL3 version vendored in `src/engine/3rdparty`

**Comment by Wolf3s** [comment]
> First issue is due to this in `m_menu.c`:
> 
> ```
> #ifdef _WIN32
> #include "i_xinput.h"
> #endif
> ```
> 
> It compiles when removing the `#ifdef`
> 
> The `SDL_WaitSemaphore` issue is caused by not using the expected SDL3 version by the code (yours is too recent!). In up to date version this function is `void`:
> 
> https://wiki.libsdl.org/SDL3/SDL_WaitSemaphore
> 
> Until SDL3 is stable (or there is a new official preview release used by this project), there is bound to be such issues on Linux if not compiling with the SDL3 version vendored in `src/engine/3rdparty`

I hated when atsd didn´t care about keeping SDL2 while SDL3 is still unstable...

**Comment by atsb** [comment]
Yesterday I made SDL3 changes to reflect the bleeding edge version.

Yeah those ifdefs are an issue, I will fix that.

**Comment by atsb** [comment]
> > First issue is due to this in `m_menu.c`:
> > ```
> > #ifdef _WIN32
> > #include "i_xinput.h"
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It compiles when removing the `#ifdef`
> > The `SDL_WaitSemaphore` issue is caused by not using the expected SDL3 version by the code (yours is too recent!). In up to date version this function is `void`:
> > https://wiki.libsdl.org/SDL3/SDL_WaitSemaphore
> > Until SDL3 is stable (or there is a new official preview release used by this project), there is bound to be such issues on Linux if not compiling with the SDL3 version vendored in `src/engine/3rdparty`
> 
> I hated when atsb didn´t care about keeping SDL2 while SDL3 is still unstable...

Well the teething problems are solved moving to an unstable API and making small incremental changes once a month instead of going full speed into a new API and having to do all the work immediately.

**Comment by Wolf3s** [comment]
> > > First issue is due to this in `m_menu.c`:
> > > ```
> > > #ifdef _WIN32
> > > #include "i_xinput.h"
> > > #endif
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It compiles when removing the `#ifdef`
> > > The `SDL_WaitSemaphore` issue is caused by not using the expected SDL3 version by the code (yours is too recent!). In up to date version this function is `void`:
> > > https://wiki.libsdl.org/SDL3/SDL_WaitSemaphore
> > > Until SDL3 is stable (or there is a new official preview release used by this project), there is bound to be such issues on Linux if not compiling with the SDL3 version vendored in `src/engine/3rdparty`
> > 
> > 
> > I hated when atsb didn´t care about keeping SDL2 while SDL3 is still unstable...
> 
> Well the teething problems are solved moving to an unstable API and making small incremental changes once a month instead of going full speed into a new API and having to do all the work immediately.

Yeah but at least you could keep the SDL2 api aswell since some linux buddy´s will have problems with compatibility anyway it´s your way.

**Comment by atsb** [comment]
I focus where the playerbase is.  There are far more Windows players than Linux players, and so choices that benefit the majority are in my best interest.

**Comment by StevenSYS** [comment]
The latest commit compiles but freezes on the copyright info.

~~I've ended up...~~

- ~~Putting the changes from 030c12f 87e7a32 397f6f8 ec0c6b5 to c0c790a,~~
- ~~Changing `void` to `int` on line 557 in `src/engine/3rdparty/Includes/SDL3/SDL_mutex.h`,~~
- ~~And then adding `-Isrc/engine/3rdparty/Includes` to the C flags in the Makefile.~~

~~I'll be using this until something proper gets added.~~

**Comment by bubbleguuum** [comment]
There is a new official SDL3 v3.1.3 preview version available. Maybe it would be a good idea to have Doom64EX-Plus use it and stick to only official previews until SDL3 is properly released. That would make updating packages for rolling distros such as openSUSE manageable.

**Comment by StevenSYS** [comment]
The latest commit compiles but just freezes on the copyright info thing.

**Comment by atsb** [comment]
I'll take a look..  maybe it is a linux thing..

**Comment by StevenSYS** [comment]
I updated to the latest commit of SDL3 and it gives me an error about `SDL_BUTTON` in `i_sdlinput.c` line 227.

**Comment by bubbleguuum** [comment]
Confirming the same thing, freeze after logo, latest git compiled against SDL v3.1.3 on openSUSE TW.

**Comment by bubbleguuum** [comment]
> I updated to the latest commit of SDL3 and it gives me an error about `SDL_BUTTON` in `i_sdlinput.c` line 227.

Needs to be replaced by `SDL_BUTTON_MASK`

**Comment by StevenSYS** [comment]
I just did and it compiles now.

Edit: I also made a pull request #275

**Comment by atsb** [comment]
Can confirm that SDL 3.1.3 crashes it on startup.  Will need to look into this.

**Comment by atsb** [comment]
Fixed!
