### ISSUE TITLE
vsync handling vs input lag

### ISSUE THREAD

**Issue by bubbleguuum** [atsb/Doom64EX-Plus#279]
I noticed that the only way to get entirely rid of input lag on my NVIDIA RTX card is to force vsync off externally.
That's the case on Linux and Windows.

- on Windows this can be done  in the NVIDIA Control Panel, creating a new profile for doom64ex+.exe in "Manage 3D Settings > Program settings > Add" and setting "Vertical Sync" to "Off". 

- on Linux, vsync can be controlled in different ways, by order of precedence:
   - `__GL_SYNC_TO_VBLANK=0` environment variable
   -  via the `nvidia-settings` program, disabling `Sync to VBlank` checkbox in the `OpenGL Settings` panel
   
Also, specific to Linux is that some compositors (such as `picom`) may cause additional input lag. For `picom` (which is a standalone compositor) it can be fixed killing picom before running the game.

IMHO, the problem is that the game starts in an undefined vsync state (it can be on or off) and it cannot be changed in game with a setting in a menu or via a cvar. This is problematic because whether the game will start with vsync on or off is non-deterministic by default.

According to my tests on Linux, vsync can be trivially disabled calling `SDL_GL_SetSwapInterval(0)` just after `SDL_GL_CreateContext` in `i_video.c`.

But the question is do we want to force v-sync off by default ? It has the advantage of entirely fixing input lag (assuming it is not force enabled externally) but has the drawback of resulting in super high framerates (possibly in the thousands) , possibly causing high CPU usage (more noticeable on laptops in particular, triggering fans). vsync off would make more sense with a built-in framerate cap implemented in-game at maybe 240 by default. 

What's you opinion on this? I think vsync on or off should be a user setting in the menu and with a user defined frame cap. 
vsync should be disabled by default with a frame cap of 240 to fix input lag without taxing the CPU too much.
But then there is the separate issue of massive input lag with vsync on, on Windows and Linux, no matter what. That's not the case for gzdoom for example.

**Comment by atsb** [comment]
I don't get input lag at all on Windows with vsync on, not with my low dpi or high dpi mouse.  It is perfectly smooth.  On linux, it is acceptable, but then I am also not really so bothered about it, it never annoyed me and always felt precise.

I am not a fan of disabling vsync as standard.  It will be even worse for some mice, where each torn frame will cause judders.  I also dislike framerate limiters that don't match the refresh rate of monitors.  I don't have a 244hz screen and tearing frames is pretty disgusting.  While we do have double buffering which would help, it is not a solution.

I'd be in favour of forcing vsync on by default.

This NVidia issue is in the README, on AMD and Intel GPU's (I am an ARC user) it is perfectly fine..  and with NVidia's state of support for Linux, all we are doing is chasing a tail, because NVidia will never fix what they don't support.

**Comment by atsb** [comment]
I've implemented the change.

**Comment by bubbleguuum** [comment]
Thanks for adding this !

I agree, vsync on is a saner default than it being off, even if some people might get high input lag out of the box (especially on 60Hz monitors). At least they can try with vsync off in-game now, instead of having to tinker with system settings. If needed, framerate can be capped with RTSS (on Windows) or other external framerate limiters.
On the same PC, gzdoom (using the OpenGL renderer) has no input lag with vsync on, thus why EX+ has very obvious input lag with it on remains a mystery. That's on a 4K 60 Hz G-Sync monitor. The only "fix" to have impeccable input is to play with vsync off.

**Comment by bubbleguuum** [comment]
I have a workaround for Linux NVIDIA input lag with vsync on in my last PR.

Here's the long explanation of my investigations with input lag and NVIDIA after many Google searches and experimenting, on Linux except for the last paragraph:

First, I confirm that GZDoom does not have input lag with vsync on.

Looking at its code, the reason is that it calls `glFinish()` [before or after `SDL_GL_SwapWindow()`](https://github.com/ZDoom/gzdoom/blob/24792913ca894aa6799ebaa01728eb0f91f225b5/src/common/rendering/gl/gl_framebuffer.cpp#L260). 
Without `glFinish()` on NVIDIA (and maybe others), there can be many frames queued up in advance, resulting in heavy input lag.

I verified that using `glFinish()` also fix input lag in EX+ with vsync on. But it results in 100% CPU usage of single core (also observed in GZDoom), which is NVIDIA specific. This can be worked-around setting [`__GL_YIELD=USLEEP`](https://download.nvidia.com/XFree86/Linux-x86_64/560.35.03/README/openglenvvariables.html) environment variable that is NVIDIA specific.

That issue can also be fixed without using `glFlush()`, by using the `__GL_MaxFramesAllowed=1`  environment variable which limits max frame ahead rendered, also NVIDIA Linux specific. That's the solution I used in the PR as it is the least intrusive and NVIDIA only (and it also seems a slightly bit more CPU efficient than the `__GL_YIELD=USLEEP` solution).

All of this is Linux specific and on Windows the problem remain. I verified that in GZDoom using `glFinish()` also uses 100% of a core with vsync on. I could not find an external solution on Windows to have vsync on without input lag. In the NVIDIA CP, changing "Low latency" to "on" should be equivalent to `__GL_MaxFramesAllowed=1`  but it does not work. 
The only thing that can fix it on Windows is to use `glFinish()`. Maybe it would be a good idea to do this, or have it available via a CVAR.

**Comment by atsb** [comment]
I tried glFinish(); after the swapping window and I do not get 100% cpu usage..  yeah, definitely an NVidia thing, so stupid..  I'll find a workaround to add it for all GPU's except NVidia, maybe by getting the GPU vendor via opengl and then cancelling that call for nvidia users..

So glad I don't have an NVidia card..  what a nightmare.

**Comment by bubbleguuum** [comment]
Yes it's a bit of a minefield. Though 80% of people  have a NVIDIA GPU, so it is worth going the extra trouble
to make their experience the best it can be out of the box.

I would call `glFinish()` with NVIDIA (after all, GZDoom is doing it):

- only on Windows (since on Linux there is the workaround of my last PR)
- only if vsync is on

Again, this is the only way to not have horrible input lag on Windows out of the box with vsync on with NVIDIA. And it is not just my system.

**Comment by atsb** [comment]
Would be better if people stopped buying NVidia GPU's... or that company fixed their mess.
