### ISSUE TITLE
Making Doom64EX-Plus work with ALSA

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#34]
During the tests I made just today I noticed that I needed to install Pulseaudio for sound and music to work. Otherwise, both were totally absent, and also console output said these things:
```
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable
fluidsynth: error: Failed to create PulseAudio connection
```

Do you think it could be possible to make Doom64EX-Plus to work with ALSA as well, or with the "ALSA Pulseaudio emulator" Apulse?

Thanks very much again.

**Comment by nixRidge** [comment]
Just built this project and found out it won't run without libpulsecommon-16.1.so, bummer! I've moved on to PipeWire as many others undoubtedly have as well, so it'd be nice to not depend on Pulse :)

Downloaded libpulse from my distro's [package repo](https://archlinux.org/packages/extra/x86_64/libpulse/) and just copied the required file to /usr/lib, works like that at least.. lol (Probably not a recommended fix, feels like a stupid thing to do but what do I know)

**Comment by atsb** [comment]
It depends on this due to fluidsynth.  The audio backend is entirely dependent on fluidsynth for everything.

Id love to move on from it and make SDL2 Mixer the backend and keep the soundfont support but this isn’t a small change.

I really hate fluidsynth.

**Comment by nixRidge** [comment]
Yes, I see now, I was just reading about FluidSynth and came to edit my comment... Can see why you don't like it :s

Sorry for trivializing the issue!

**Comment by atsb** [comment]
No worries at all.  It looks small but it’s a hog when it comes to dependencies.  It’s on the plan, one day our dreams will be reality :)

**Comment by atsb** [comment]
So today I have pushed into the unfuq_fluidsynth branch a commit that will make ALSA the default choice on Windows.  I did some testing and ALSA is much better at handling the audio than Pulseaudio is.  There are no crackling sounds or skips that Pulseaudio produces.

**Comment by atsb** [comment]
I will close this and merge later.
