### ISSUE TITLE
Issue: Configuartion file fails to create and load on Ubuntu 22.04LTS

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#35]
https://user-images.githubusercontent.com/75867486/201476393-f2e283e6-dd39-4660-a611-d81bbfee636b.mp4

**Comment by atsb** [comment]
It fails to create it because we now save the config file in the same directory.  Since you place it in the system directory, it would need sudo rights to create it.

I will add a compile macro to allow the SDL_BasePrefPath for those who want to 'install' it

**Comment by atsb** [comment]
Fixed: https://github.com/atsb/Doom64EX-Plus/commit/2d6a2b34b8f79f7e97f2b02ffc59f5de83f1b7d2

**Comment by Wolf3s** [comment]
> It fails to create it because we now save the config file in the same directory. Since you place it in the system directory, it would need sudo rights to create it.
> 
> I will add a compile macro to allow the SDL_BasePrefPath for those who want to 'install' it

It's a cool fix that you made thanks.
