### ISSUE TITLE
"Secret items" not being counted

### ISSUE THREAD

**Issue by bfg01** [atsb/Doom64EX-Plus#38]
I know I mentioned earlier that the *item picking* "secret triggers" were now functional, but I think this was not the case.

Or at least not totally: I realized that at that moment I was testing on the skill level 2. When getting back to skill level 4, "secret items" were not being counted, albeit "secret sectors" still did.

So could it be that it depends on skill level? A quite good way to test is MAP10, where **all** the secrets are items rather than sectors.

Thanks again.

EDIT: perhaps the perfect map to test this issue is MAP14: it has only one secret, and it's an item. Yet secret count is 8%...

**Comment by atsb** [comment]
I tried this one (MAP14).  After getting the BFG and exiting, my secret count was 100%.  I did it again without getting the BFG and it was 0%.  

Windows 10, 64bit.

I did it on skill 1, 2 and 4.  No difference.  Item counts as a secret.  I'll try it on Linux and see if its something platform specific.

**Comment by bfg01** [comment]
> I did it on skill 1, 2 and 4. No difference. Item counts as a secret. I'll try it on Linux and see if its something platform specific.

Could you perhaps try there to see if it's a "platform" issue?
Thanks.

**Comment by atsb** [comment]
I've done some testing and this no longer happens on any system that I can tell.

**Comment by bfg01** [comment]
I think I finally managed to recreate the issue more faithfully:
it's precisely when using the load game function.

Say, in MAP14 since officially beginning the level, literally just one step away from the exit "teleporter":
--no load/save at all, or only save, step in the exit: 100% secrets
--load the game, step in the exit: 8% secrets, or 50% like just today (I have no idea if this is being random...)

Hope this helps.

**Comment by atsb** [comment]
Weird!  I’ll look into this area then.  I also want to add a “you have found a secret item” message.

**Comment by atsb** [comment]
![sshot012](https://user-images.githubusercontent.com/44937323/209969208-d82ca46e-dbba-4d87-a905-a899922df836.png)

100% secrets on Outpost Omega.

Fixed.
