### ISSUE TITLE
Switch xinput to SDL_GameController

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#42]

**Comment by atsb** [comment]
Good idea!  SDL_GameController is multi platform and supports most of the popular controllers.  Xinput is windows only and has a disgusting hacky API.  I’ll get started with this

**Comment by Wolf3s** [comment]
> Good idea! SDL_GameController is multi platform and supports most of the popular controllers. Xinput is windows only and has a disgusting hacky API. I’ll get started with this

I tried sometime once but i didn't make it :(

**Comment by atsb** [comment]
No worries, I'll take care of it.  Good news is that, without that XInput stuff, we can remove the gamepad specific menu entries as I'll use SDL_Joystick, so the gamepad will use the same sensitivity as the mouse.  Nice and easy

**Comment by atsb** [comment]
So I'm taking this from one of my other source ports (Pooch).  The implementation there goes back to WinMBF and is super simple and fits right into the EX+ codebase.  Some features may not be completely 100% the same, but this can be done after I get it working.  I'll do a PR once that happens and we can go from there.

**Comment by Wolf3s** [comment]
> So I'm taking this from one of my other source ports (Pooch). The implementation there goes back to WinMBF and is super simple and fits right into the EX+ codebase. Some features may not be completely 100% the same, but this can be done after I get it working. I'll do a PR once that happens and we can go from there.

i will try to see the launcher and support to linux

**Comment by Wolf3s** [comment]
Closed the SDL_GameController is working although it has some minor glitches but i think it´s the conflict of the keyboard
