### ISSUE TITLE
Animating Pallette change

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#48]
So while Erick fixed a lot of things about animating palette's, the horizontal palette's are broken again and no longer animate (wall palette's, doorframe lights).  This is done solely in i_png.c

This whole code is generally a giant pain.  It should be replaced with code that will simply read the palette's and allow them to animate normally.  It'll need to do this on all platforms and architectures.

**Comment by atsb** [comment]
For this I've done some investigation.  It definitely isn't the ANIM lump nor is it any of the int64_t casts to the ANIM lump reader.  This issue is solely in the i_png.c code.  It simply is not showing the animated difference.  At this point, I'm wondering if we could simply export those images and convert them to 8bit so that they aren't hit by this 'if 4bit' clause.  I'm fairly certain if they are 8bit animated textures, then it would work.

**Comment by Wolf3s** [comment]
> For this I've done some investigation. It definitely isn't the ANIM lump nor is it any of the int64_t casts to the ANIM lump reader. This issue is solely in the i_png.c code. It simply is not showing the animated difference. At this point, I'm wondering if we could simply export those images and convert them to 8bit so that they aren't hit by this 'if 4bit' clause. I'm fairly certain if they are 8bit animated textures, then it would work.

Oh s**t here we go again.

**Comment by atsb** [comment]
It is really pissing me off :D the one last thing

**Comment by Wolf3s** [comment]
> It is really pissing me off :D the one last thing

Yeah this really pisses off :D

**Comment by atsb** [comment]
Animated palettes are FIXED!  Thanks to Immorpher who converted the 4bit images to 8bit.  I'll be completely removing 4bit animated code and will change how the textures animate.  Instead lets just cycle to defined images instead.

**Comment by Wolf3s** [comment]
> Animated palettes are FIXED! Thanks to Immorpher who converted the 4bit images to 8bit. I'll be completely removing 4bit animated code and will change how the textures animate. Instead lets just cycle to defined images instead.

Congradulations
