### ISSUE TITLE
Volume is really quiet

### ISSUE THREAD

**Issue by OpenRift412** [atsb/Doom64EX-Plus#53]
Both the sound and music volumes appear to be really quiet, even at max. Using Win64 build.

**Comment by thekovic** [comment]
I can confirm I observe the same behaviour on Win64 build (compiled myself). The audio with the volume sliders maxxed out is about 66% quieter than the same audio settings on the official PC remaster.

**Comment by atsb** [comment]
I think I know why.  I changed the sliders to increase the sound by +1 each time so that it is a smooth action and doesn't skip positions, however this would also affect the maximum possible.  I'll change it so it increases the sound by say +20.

**Comment by atsb** [comment]
I've uploaded a fixed 3.6.5 for win64 with the volume more than doubled.  The sliders go up by +20 and -20 each time, so max'd out is pretty loud.

**Comment by atsb** [comment]
I did some experimenting with even higher values, but only a little higher than the current 300, fluidsynth will cut out completely and stop playing.  We could probably bump it to say 350 as a maximum if it is still a bit too quiet, but this is absolutely a fluidsynth limitation.

**Comment by thekovic** [comment]
I built latest main and the music volume is much better. Maxxed out slider is almost as loud as the Remaster, within margin of error of shoddy ears for me, I'd say. Gun sounds are still a bit too quiet imo, and seem to get quieter if you shoot continuously. This seems to me like fluidsynth being shite so I'd perhaps not worry about it too much if the whole audio system is going to be replaced eventually.

**Comment by atsb** [comment]
We will be replacing it with SDL Mixer by the next release.  Agreed, sound fx are still quiet and change depending on certain factors.  Fluidsynth sucks.

**Comment by atsb** [comment]
3.6.5.1 binary should fix this.
