### ISSUE TITLE
Move strings to external .txt or .xml files to be read

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#61]
This aids translation ability, currently everything is hardcoded to English.  External txt or xml files is probably the most cross-platform way to do this.

**Comment by Wolf3s** [comment]
> This aids translation ability, currently everything is hardcoded to English. External txt or xml files is probably the most cross-platform way to do this.

Well we have atm the W_WriteTextFile but it sucks since it does not add the secondary char.

**Comment by Wolf3s** [comment]
i´m gonna see the xbmc to see how it works

**Comment by atsb** [comment]
I was thinking about libxml2 and reading strings from xml files

**Comment by Wolf3s** [comment]
> libxml2

Good lib.

**Comment by Wolf3s** [comment]
This lib is more simple however there´s not much examples of it: https://github.com/ooxi/xml.c
