### ISSUE TITLE
Feature request: make non-bindable keys bindable

### ISSUE THREAD

**Issue by id259** [atsb/Doom64EX-Plus#74]
Currently F1, F2, F5-F7, F11, T and 9 keys are hardcoded to various actions and cannot be rebound. It wold be nice if they could be rebound like any other key.

Also, I don't know if it's worth its own issue, but it would be great if sv_fastmonsters sv_respawn sv_respawnitems sv_nomonsters cvars wouldn't reset back to zero on every launch so it is possible to play with fast monsters without using launcher or command line parameter.

**Comment by atsb** [comment]
Thanks!  I'll do as many of these as possible.

**Comment by id259** [comment]
Thank you.

**Comment by atsb** [comment]
This is done in the latest 2 commits.  I will do a release soon in the next few days with this feature included.
