### ISSUE TITLE
Game cannot find pulse

### ISSUE THREAD

**Issue by iguanatamer** [atsb/Doom64EX-Plus#87]
Hi,

I am on Arch Linux and I am getting this error. 

./DOOM64EX-Plus: error while loading shared libraries: libpulsecommon-16.1.so: cannot open shared object file: No such file or directory

It seems that it is looking for the library in a different place.

**Comment by atsb** [comment]
Was this compiled yourself?  Doom64ex+ uses fluidsynth on Linux (the full one) and this uses libpulse.  On Arch I would definitely recommend compiling it yourself as I only test on Ubuntu and Debian.

**Comment by iguanatamer** [comment]
Yes I did compile it myself.

**Comment by atsb** [comment]
Looks like Arch then calls libpulsecommon something different.  Maybe without the 16 in the name.  I really hate it when distro's change standardised library names like this.

**Comment by atsb** [comment]
I believe this is fixed right, from discord.  I'll close but if it happens again, please reopen :)

**Comment by iguanatamer** [comment]
Still getting the same error when building from main :(

**Comment by Omnisthetics** [comment]
I got the same error after compiling it myself today on Arch, but I fixed it by symlinking libpulsecommon to /lib/.

`ln -s /lib/pulseaudio/libpulsecommon-16.1.so /lib/libpulsecommon-16.1.so`

**Comment by atsb** [comment]
That's weird, so Arch doesn't have a pulseaudio directory.
