### ISSUE TITLE
WadGen tool in v3.4.0 doesn't work but an older version does

### ISSUE THREAD

**Issue by ViperAcidZX** [atsb/Doom64EX-Plus#9]
Another problem I ran into is the included WadGen tool provided in the v3.4.0 release always fails to create the necessary files to run the port. I tried different ROM dumps of Doom 64 and nothing seems to work, so I had to download v3.3.0 and use its WadGen tool instead which gave me no problems at all with creating the required files for the port.

**Comment by atsb** [comment]
I have now added the older WadGen using libpng1.5 to the release:
https://github.com/atsb/Doom64EX-Plus/releases/tag/3.4.0

This one should work fine.  I've decided to stop supporting it as it really is a pain, this one will work fine for the intended purpose.
