### ISSUE TITLE
Saving/Loading is broken

### ISSUE THREAD

**Issue by atsb** [atsb/Doom64EX-Plus#92]
Seems to have occured at the merge of the fancy new library.  I'll debug on Linux later and see where the issue is.

**Comment by atsb** [comment]
On Windows it complains here:

![image](https://user-images.githubusercontent.com/44937323/209343949-64ae093d-1b38-4b17-9f13-55a68c618375.png)

**Comment by Wolf3s** [comment]
> On Windows it complains here:
> 
> ![image](https://user-images.githubusercontent.com/44937323/209343949-64ae093d-1b38-4b17-9f13-55a68c618375.png)

~~Fuck~~
