### ISSUE TITLE
Nintendo Switch does not build properly

### ISSUE THREAD

**Issue by Wolf3s** [atsb/Doom64EX-Plus#99]
I was testing here a shell file of Doom64EX+ and when i just build it´s does not generate nothing looks like i´m gonna appeal to a Makefile

**Comment by atsb** [comment]
Agreed.  Makefile will be the way to go.  I was mostly testing out the SDK, making sure I had all the libraries set up etc..  big issue though is Switch does not support plain OpenGL.  It only had GLFW in the SDK or GLES.

**Comment by Wolf3s** [comment]
> Agreed. Makefile will be the way to go. I was mostly testing out the SDK, making sure I had all the libraries set up etc.. big issue though is Switch does not support plain OpenGL. It only had GLFW in the SDK or GLES.

No, this is the minnor issue. the great problem is the shader stuff some consoles doesn´t support or it support yest but it´s another shader language like HLSL(High Level Shader Language).
I will make a list here of consoles that doesn´t support the shader language.
Consoles that does not support shader language
Playstation 2
Microsoft Original Xbox
Nintendo Gamecube
DreamCast
Consoles that supports shader language
Xbox 360(HLSL) ps: this guy would be a hard work tough see here: [why](https://github.com/brentdc-nz/Half-LifeX/issues/5#issuecomment-1213239011)
PS3

**Comment by atsb** [comment]
I also don't know HLSL at all, mostly it is a Windows thing.

**Comment by Wolf3s** [comment]
> I also don't know HLSL at all, mostly it is a Windows thing.

In real it´s a windows/xbox 360 thing

**Comment by atsb** [comment]
Guess we could focus on Vita and Switch support as that should be fairly easy as they both support standard Linux libraries and headers for the most part.  Shaders aren’t an issue on Vita either..  especially since I’ve almost eradicated the texture combiners.

**Comment by Wolf3s** [comment]
> Guess we could focus on Vita and Switch support as that should be fairly easy as they both support standard Linux libraries and headers for the most part. Shaders aren’t an issue on Vita either.. especially since I’ve almost eradicated the texture combiners.

Yeah, also did you tried to contact again with Rinnegatamante?

**Comment by atsb** [comment]
Not yet.  They didn’t seem to want to bother as they ported the C++ version and will need to redo it from scratch for this one

**Comment by Wolf3s** [comment]
> Not yet. They didn’t seem to want to bother as they ported the C++ version and will need to redo it from scratch for this one

or at least merge some code of them.

**Comment by atsb** [comment]
I’ll take a look and see what so can merge

**Comment by Wolf3s** [comment]
Closed but i will create a sub issue but related to opengl stuff
